### ISSUE TITLE
Błędy SQL przy kliknięciu Finanse-->Płatności BillTech

### ISSUE THREAD

**Issue by interduo** [BillTechPL/lms-billtech-plugin#11]
![billtech_payment_list](https://user-images.githubusercontent.com/17087236/38681070-2bcfd698-3e68-11e8-8f7f-435fced6ae16.png)

Złe SQL Querry?

**Comment by MKaciuba** [comment]
To zapytanie chyba nie ma nic wspólnego z wtyczką BillTech

**Comment by interduo** [comment]
To w takim razie muszę to skonsultować.

**Comment by interduo** [comment]
Faktycznie - problem nie leży po stronie kodu BillTech. 
Źle zdiagnozowałem miejsce wystąpienia błędu.
