### ISSUE TITLE
brak constrainta w schemacie DB

### ISSUE THREAD

**Issue by interduo** [BillTechPL/lms-billtech-plugin#123]
W https://github.com/BillTechPL/lms-billtech-plugin/blob/master/doc/lms.pgsql#L20
brakuje
`cash(id) REFERENCES cash(id) ON DELETE SET NULL`.

Bez tego w przypadku usunięcia ręcznego wpłaty tymczasowej (np. z poziomu UI LMS i historii operacji) - zostają śmieci w DB.
Wydaje mi się, że rozwiązuje to też finalnie problem w oznaczaniu płatności jako zapłaconej z UI z formularza `m=billtechpaymentlist`

**Comment by interduo** [comment]
to zostało dodane w https://github.com/BillTechPL/lms-billtech-plugin/pull/124

**Comment by cybernetwmw** [comment]
@smiecielica-billtech dorzuć jeszcze to do aktualizacji schematu DB
