### ISSUE TITLE
Opłać teraz %billtech_balance_btn %billtech_btn niejednoznaczny opis przycisków billtech

### ISSUE THREAD

**Issue by interduo** [BillTechPL/lms-billtech-plugin#127]
Te dwie zmienne generują ten sam opis:
%billtech_balance_btn %billtech_btn

Moim zdaniem to powinno być zrobione tak że:
%billtech_balance_btn --> tu powinien być opis na przycisku "Opłać saldo"
%billtech_btn --> tu powinien być opis na przycisku "Opłać dokument" (dla przypomnienia można tez wysyłać proformy i noty)

**Comment by interduo** [comment]
@smiecielica-billtech @pablos-billtech ogarniecie to?:)

**Comment by piotrwarzachowski-billtech** [comment]
@interduo  działam

**Comment by interduo** [comment]
Super! Kiedy mozemy liczyć na przygotowanie tej dość trywialnej zmiany?

**Comment by smiecielica-billtech** [comment]
@interduo Dzień dobry, zmiana została wprowadzona, jest na masterze. Pozdrawiam!

**Comment by interduo** [comment]
@smiecielica-billtech czy okazji przejrzeliście równeż ebok pod kątem wprowadzenia możliwych "udoskonaleń" w tym zakresie? :)

**Comment by interduo** [comment]
???
