### ISSUE TITLE
BillTechPayment nie kasujące się rekordy

### ISSUE THREAD

**Issue by interduo** [BillTechPL/lms-billtech-plugin#16]
Mamy następujący problem:

Mamy trochę płatności BillTechowych które wiszą u klienta. W momencie zaksięgowania wpłaty przez bank i importu do LMS wpłaty nie znikają.

Są to np. wpłaty:

```
customerid, data, kwota
| 23 | 2018-02-21 16:48:42 | 5.00 |
| 2950 | 2018-12-13 11:54:50 | 52.00 |
| 1867 | 2018-12-19 21:50:01 | 49.00 |
| 1867 | 2018-12-19 21:54:28 | 49.00 |
| 3914 | 2019-01-10 18:33:47 | 49.90 |
| 2950 | 2019-02-14 18:20:48 | 52.00 |
| 1906 | 2019-02-16 21:17:10 | 59.00 |
| 1243 | 2019-04-09 09:38:32 | 72.50 |
| 1906 | 2019-04-25 17:22:51 | 59.00 |
```

Kliknięcie z poziomu gui w lms -> finanse -> płatności billtech -> oznacz jako nierozliczoną powoduje dodanie kolejnej pozycji do rejestru cash klienta - sprawdzone na kliencie 00023.

Jak możemy zdiagnozować i rozwiązać problem?

Efekt finalny jest bardzo brzydki najczęściej klient ma nadpłatę w wysokości ostatniej opłaty (podwojona ostatnia wpłata).

**Comment by MKaciuba** [comment]
Jaka jest wartość billtech.cashimport_enabled w configu? Za obsługę cash import odpowiada BillTechPaymentCashImportHandler.php. Wyszukuje w polu description wzorca "/ref:(\d{8}-\d{6})/". Czy przy imporcie pole description zawiera taki wzorzec?

**Comment by interduo** [comment]
Po kolei:
- do tej pory nie mieliśmy tej opcji w ogóle (dopisałem)
- description przy imporcie wpłat jest 
`r|ef:20190509-658767`
(chyba nie łapie się w parser)

**Comment by interduo** [comment]
Kiedy się uruchamia: `processCashImport` oraz czy da się uruchomić sprawdzanie wpłat tak by nie sprawdzać tego ręcznie?

**Comment by MKaciuba** [comment]
Od początku:
Pierwotnie, przed implementacją processCashImport, mechanizm działał tak:

1. Klient wykonuje płatność za saldo lub konkretną fakturę za pośrednictwem BillTech
2. LMS okresowo odpytuje BillTech o nowe ukończone płatności
3. Ukończona płatność powoduje dodanie odpowiedniego wpisu w tabelce billtech_payment oraz cash - to zmienia saldo klienta
4. Jeśli ISP korzysta z cashImport to w momencie importu powstaje duplikat w tabelce cash i klient widzi nadpłatę. By temu zapobiec należy ręcznie oznaczyć odpowiednią płatność billtech jako rozliczoną co powoduje usunięcie powiązanego z nią wpisu w cash - nie ma duplikatu. Dodatkowo funkcjonuje mechanizm, który automatycznie rozlicza billtech_payment po określonym czasie od wykonania (billtech.payment_expiration - domyślnie 5 dni).

Funkcja integracji wtyczki BillTech z mechanizmem cashimport jest eksperymentalna. Jej działanie polega na automatycznym rozliczaniu billtech_payment na podstawie numeru referencyjnego zawartego w tytule przelewu. W przypadku korzystania z tej funkcji najlepiej ustawić billtech.payment_expiration = "never" - wtedy billtech_payment nie będą rozliczane automatycznie. 

Rzeczywiście w przykładowym tytule płatności znak "|" sprawia, że wzorzec nie zostaje wykryty. Na pewno tytuły płatności generowane przez BillTech nie zawierają tych znaków. W systemach bankowych pole tytuł przelewu często składa się tak na prawdę z 4 pól po 35 znaków nawet jeśli nadawca przelewu wpisuje wartość w pojedyncze pole na 140 znaków. Tak się składa, że odstęp pomiędzy "|" w przykładzie wynosi dokładnie 35. Są dwie możliwości, albo to bank w wygenerowanym wykazie wstawia te znaki albo robi to skrypt cashimport. Mogę zmodyfikować tego regexa, żeby dopuszczał znak "|" w dowolnym miejscu i go ignorował ale chciałbym wiedzieć skąd to się wzięło (bank/skrypt) żeby ocenić czy na pewno zawsze będzie to ten sam znak.

**Comment by interduo** [comment]
A jakiś pomysł dlaczego te stare wpłaty po prostu nie wyleciały z salda klienta?

**Comment by MKaciuba** [comment]
Jaki jest status powiązanych płatności BillTech (billtech_payment)?

**Comment by interduo** [comment]
Dlaczego userid w polu cash jest ustawiane raz tak raz inaczej? 
Powinno to być ustawialne ze zmiennej lub mieć zawsze wartość NULL.

**Comment by interduo** [comment]
```
ariaDB [lmsdb]> SELECT * FROM billtech_payments WHERE cashid = 370136;
Empty set (0.00 sec)

MariaDB [lmsdb]> SELECT id,customerid,value,userid FROM cash WHERE id=370136;
+--------+------------+-------+--------+
| id     | customerid | value | userid |
+--------+------------+-------+--------+
| 370136 |       1867 | 49.00 |   NULL |
+--------+------------+-------+--------+

```

**Comment by interduo** [comment]
Ok, rozumiem już dlaczego nie rozliczyła się automatycznie.

Ustawię sobie:
`billtech.payment_expiration = 5 dni` i zobaczymy czy nadal takie wpłaty będą zostawać gdzieś w logu.

**Comment by MKaciuba** [comment]
Skoro nie ma powiązanego wpisu w billtech_payments to czy na pewno wpłata została wykonana przez BillTech?

> Dlaczego userid w polu cash jest ustawiane raz tak raz inaczej?
> Powinno to być ustawialne ze zmiennej lub mieć zawsze wartość NULL.

Przeoczenie. Poprawiam.

**Comment by interduo** [comment]
Co do wzorca - ja zmodyfikowałem go u nas wycinając "r" ale po prostu skrypt mógłby nie brać pod uwagę znaku | jak również przecinków szukając frazy bo te najczęściej banki dorzucają a wzorzec mógłby być nadal taki sam.

**Comment by MKaciuba** [comment]
> Co do wzorca - ja zmodyfikowałem go u nas wycinając "r" ale po prostu skrypt mógłby nie brać pod uwagę znaku | jak również przecinków szukając frazy bo te najczęściej banki dorzucają a wzorzec mógłby być nadal taki sam. Co Ty na to?

Sprawdź proszę czy działa na branchu https://github.com/BillTechPL/lms-billtech-plugin/tree/cashimport

**Comment by interduo** [comment]
ok, sprawdzę

To jeszcze zostało powiązane z tym zgłoszeniem: 
https://github.com/BillTechPL/lms-billtech-plugin/issues/17 (nie wiem czy widziałeś to)

**Comment by interduo** [comment]
Dzięki za poprzednie commity. Czekam aż trafią do głównego brancha.

**Comment by interduo** [comment]
@MKaciuba wrzuć proszę do głównego brancha te commity

**Comment by MKaciuba** [comment]
https://github.com/BillTechPL/lms-billtech-plugin/pull/18
