### ISSUE TITLE
Nieprawidłowe działanie funkcji zaznacz/odznacz jako nierozliczoną

### ISSUE THREAD

**Issue by interduo** [BillTechPL/lms-billtech-plugin#17]
Jest:
Kliknięcie z poziomu gui w lms -> finanse -> płatności billtech -> oznacz jako nierozliczoną powoduje dodanie kolejnej pozycji do rejestru cash klienta.

Powinno być:
Kliknięcie z poziomu gui w lms -> finanse -> płatności billtech -> oznacz jako nierozliczoną **nie powoduje** dodanie kolejnej pozycji do rejestru cash klienta.

**Comment by MKaciuba** [comment]
To działa prawidłowo. Jedyna sytuacja, w której należy oznaczyć płatność jako nierozliczoną to jeśli została wcześniej omyłkowo oznaczona jako rozliczona.

**Comment by interduo** [comment]
Zauważ że ten przycisk robi dwie funkcje "zaznacz" i "odznacz". W obu przypadkach dodawany jest wpis do cash.

**Comment by interduo** [comment]
Inaczej mamy dwa przypadki:
1. Używamy przycisku "Zaznacz/odznacz jako rozliczone" w przypadku płatności rozliczonej (kolor szary).
2. Używamy przycisku "Zaznacz/odznacz jako rozliczone" w przypadku płatności rozliczonej (kolor bordo).

W każdym z tych przypadków po kliknięciu przycisku jest dodawany wpis w cash. W dodatku można to zrobić wiele razy także w saldzie klienta pojawia się nieścisłość.

**Comment by MKaciuba** [comment]
Kliknięcie przycisku dla płatności nierozliczonej powinno kasować powiązany wpis cash, a nie tworzyć nowy. Jeśli jest inaczej to jest to błąd. Spróbuję to jutro odtworzyć.

**Comment by interduo** [comment]
> Kliknięcie przycisku dla płatności nierozliczonej powinno kasować powiązany wpis cash

Mówisz o wpisie w tabeli cash której comment = "BillTech Payments" tak?

**Comment by MKaciuba** [comment]
@interduo Nie udaje mi się tego odtworzyć. U mnie działa tak:

**Płatność BillTech nierozliczona**
- Saldo klienta jest powiększone o wartość wpłaty
- w tabelce billtech_payment w kolumnie cashid jest id odpowiedniego wiersza z tabelki cash
- Zaznaczam tę płatność BillTech i klikam _Zaznacz/Odznacz jako rozliczone_ -> w billtech_payments kolumna closed zmienia się na 0, kolumna cashid na null, znika wiersz z cash, saldo klienta nie uwzględnia wpłaty BillTech

**Płatność BillTech rozliczona**
- Saldo klienta nie uwzględnia wpłaty BillTech
- Zaznaczam rozliczoną płatność BillTech i klikam _Zaznacz/Odznacz jako rozliczone_ -> dodaje się wpis w tabelce cash, id tego wpisu ląduje w billtech_payments.cashid, closed zmienia się na 0

@interduo jeśli u Ciebie działa to inaczej to czy możesz potwierdzić, że korzystacie z najnowszej, niemodyfikowanej wersji wtyczki?

**Comment by interduo** [comment]
> Płatność BillTech rozliczona

> Zaznaczam rozliczoną płatność BillTech i klikam Zaznacz/Odznacz jako rozliczone -> dodaje się wpis w tabelce cash, id tego wpisu ląduje w billtech_payments.cashid, closed zmienia się na 0

To mi nie działa. Tak jak piszesz.
Przy rozliczonych wpłatach po kliknięciu Zaznacz/Odznacz dodaje się wpis w cash "BillTech Payments" a wpłata na liście nadal widnieje jako rozliczona.

**Comment by MKaciuba** [comment]
> wpłata na liście nadal widnieje jako rozliczona.

Tak się może dziać, jeśli wpłata jest stara t.j. minęło więcej niż `billtech.payment_expiration`. Wtedy po kliknięciu od razu przestawia się spowrotem. 

Nadal nie do końca rozumiem na czym dokładnie polega problem. Czy każde kliknięcie w _Zaznacz/Odznacz jako rozliczone_ powoduje wygenerowanie nowego wpisu w `cash`, które się kumulują? Czy chodzi o to, że cały czas jest jeden wiersz w `cash, który _nie chce_ zniknąć?

**Comment by interduo** [comment]
> Tak się może dziać, jeśli wpłata jest stara t.j. minęło więcej niż billtech.payment_expiration. Wtedy po kliknięciu od razu przestawia się z powrotem.

OK nie przypuszczałem, że tak może być. To ten case do zamknięcia.

To została jedna sytuacja:
- użytkownik LMS przez pomyłkę może kliknąć Odznacz/Zaznacz (dla płatności rozliczonej), 
- łąduje wpis w tabeli Cash (comment='BillTech Payments') 
- wpłata będzie wisieć do końca świata mimo ustawionej zmiennej payment_expiration
