### ISSUE TITLE
Wtyczka BillTech powoduje błąd w eBOK

### ISSUE THREAD

**Issue by interduo** [BillTechPL/lms-billtech-plugin#19]
@olimplan i @interduo ma tą samą przypadłość jeśli chodzi o ebok i dokonywanie wpłat za pomocą ebok i przycisku BillTech.

Chodzi o błąd w SQL:
![image](https://user-images.githubusercontent.com/17087236/58188824-96a99180-7cb9-11e9-81a6-e12069bbd8ab.png)

Żeby ten błąd zaistniał - musi być wtyczka BillTech i włączony dziennik zdarzeń.

Jedyne co mi się udało zbadać to to że zgłoszenie przyszło do nas od klienta który kilka minut wcześniej dokonał wpłaty za pomocą BillTech.

Macie pomysł jak to zdebugować?

**Comment by interduo** [comment]
https://user-images.githubusercontent.com/17087236/58365706-6d128500-7ec8-11e9-8c38-91c4dd57a984.png

Zastanawiam się czy to wina wtyczki czy nie.

**Comment by MKaciuba** [comment]
![image](https://user-images.githubusercontent.com/9113506/58706946-b1fc5700-83b3-11e9-8340-862065b5eeae.png)

**Comment by interduo** [comment]
Przyszła mi na myśl sytuacja w której klient nie ma komputerów. Może to być ta sytuacja?

**Comment by interduo** [comment]
Sprawdzam ale nie udaje mi się wywołać błędu.

**Comment by MKaciuba** [comment]
> Przyszła mi na myśl sytuacja w której klient nie ma komputerów. Może to być ta sytuacja?

Nie powinno to być problemem.
https://github.com/lmsgit/lms/blob/20c61a8a72e9871d2dbf8c08be2bb6d82229ddf4/lib/LMSManagers/LMSNodeManager.php#L664

**Comment by MKaciuba** [comment]
Pytanie czy w ogóle funkcjonalność ustawiania tych ostrzeżeń jest pożądana we wtyczce. Możemy dodać na to feature flag, aby można było to całkiem wyłączyć.

**Comment by interduo** [comment]
Ten klient który mi pokazał tego loga ma 7 komputerów.
Gdzie we wtyczce jest kod uruchamiający 7 razy NodeWarn?

**Comment by MKaciuba** [comment]
https://github.com/BillTechPL/lms-billtech-plugin/blob/master/BillTechPaymentsUpdater.php#L206

**Comment by interduo** [comment]
> Pytanie czy w ogóle funkcjonalność ustawiania tych ostrzeżeń jest pożądana we wtyczce. Możemy dodać na to feature flag, aby można było to całkiem wyłączyć.

To poproszę. Wtedy będzie wiadomo przynajmniej czy ten błąd leży po stronie wtyczki czy po stronie funkcji LMS.

**Comment by interduo** [comment]
`[Sun Jun 02 21:50:27.889927 2019] [:error] [pid 6638] [client 172.16.40.5:54259] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/lms/plugins/BillTech/BillTechPaymentsUpdater.php on line 127, referer: https://interduo.pl/`

Coś takiego w logu z wczoraj...

**Comment by interduo** [comment]
Czy jest opcja wyrzucenia BillTechPaymentsUpdater.php w tło? 
Np skrypt w crontab zamiast uruchamiać go przy jakichś zdarzeniach w GUI LMS?

Dzięki temu nie pojawiłby związany z DB w GUI panelu abonenckiego.

**Comment by interduo** [comment]
I to by się zgadzało - bo w tych okolicach czasowych przyszła jedna płatność.
I błąd pojawił się przy pierwszym użyciu GUI LMS.

**Comment by interduo** [comment]
@MKaciuba https://github.com/chilek/lms-plus/issues/774#issuecomment-509189568 - zerknij na podpowiedź.

**Comment by MKaciuba** [comment]
Co jeśli transakcja jest już rozpoczęta? Czy w takim wypadku rozpoczęcie nowej nie będzie błędem?

**Comment by interduo** [comment]
Czy możecie dogadać to między sobą - jak to ma grać?

**Comment by chilek** [comment]
Sprawdźcie po powyższych poprawkach.

**Comment by interduo** [comment]
Pomogło.
