### ISSUE TITLE
Nie działa BillTechPaymentCashImportHandler

### ISSUE THREAD

**Issue by interduo** [BillTechPL/lms-billtech-plugin#20]
Mam zmienną:
`cashimport_enabled = true`

Wydaje mi się, że w:
https://github.com/BillTechPL/lms-billtech-plugin/blob/master/handlers/BillTechPaymentCashImportHandler.php#L18

Coś nie gra. Czy `|` nie powinien być escape'nięty?

Mam najnowszą wersję wtyczki.

Mam np wpłatę:
`Opłata za saldo-20190522 ID: 681 re|f:20190522-331308 dotpay: 355898 M1|278-88906 (Wpłata BS)`

**Comment by MKaciuba** [comment]
Sprawdzisz proszę czy najnowsza zmiana na https://github.com/BillTechPL/lms-billtech-plugin/tree/cashimport rozwiązuje problem?

**Comment by interduo** [comment]
Ok - wrzuciłem sobie cherry-pickiem commita, dam znać jutro czy pomogło

**Comment by interduo** [comment]
Nie działa.

```
2019/05/29 11:08 | Paweł Panas | - | +112,00 zł | - | » | 0,00 zł | BillTech Payments |  
-- | -- | -- | -- | -- | -- | -- | -- | --
2019/05/30 00:00 |   | - | +112,00 zł | - | » | 112,00 zł | Opłata za saldo-20190529 ID: 527 re\|f:20190529-045156 dotpay: 355898 M2\|443-94603 (Wpłata BS)
```

Cashimport wykonuję za pomocą skryptu `bin/lms-cashimport.php`.

**Comment by interduo** [comment]
@MKaciuba pomożesz z tym?

**Comment by MKaciuba** [comment]
@interduo jaka jest wartość w konfiguracji cashimport.autocommit? Czy możesz zweryfikować czy w ogóle ten hook jest wywoływany dodając np. jakiegoś loga do BillTechPaymentCashImportHandler->processCashImport?

**Comment by interduo** [comment]
```
SELECT * FROM uiconfig WHERE section='billtech' AND var='cashimport_enabled';
+-----+----------+--------------------+-------+-------------+----------+------+
| id  | section  | var                | value | description | disabled | type |
+-----+----------+--------------------+-------+-------------+----------+------+
| 367 | billtech | cashimport_enabled | true  |             |        0 |    7 |
+-----+----------+--------------------+-------+-------------+----------+------+
```


```
SELECT * FROM uiconfig WHERE var="autocommit";
+-----+------------+------------+-------+-------------+----------+------+
| id  | section    | var        | value | description | disabled | type |
+-----+------------+------------+-------+-------------+----------+------+
| 287 | cashimport | autocommit | true  |             |        0 |    7 |
+-----+------------+------------+-------+-------------+----------+------+
```

**Comment by interduo** [comment]
Aktualnie w systemie mam plugin zawierający commit:
1b0e307ce6fbc7fa47a8bdd50111510b9871588c

Dodałem:
w https://github.com/BillTechPL/lms-billtech-plugin/blob/master/handlers/BillTechPaymentCashImportHandler.php#L13

kod
`mail('jkl@interduo.pl','BillTechPaymentCashImportHandler.php - hook test','biltechowy handler w skrypcie billtechpaymentcashimporthandler dziala');
`
Wykonałem płatność. Płatność pojawiła się w systemie. Brak maila.

Zrobiłem revert commita 1b0e307ce6fbc7fa47a8bdd50111510b9871588c i tu również zrobiłem płatność testową czyli oba hooki są złe.

**Comment by interduo** [comment]
Handler działa. Dostałem maila po imporcie za pomocą lms-cashimport.

Płatności billtechowe są nadal nierozliczone.

**Comment by MKaciuba** [comment]
Spróbujesz jeszcze ze zmianami z brancha cashimport?

**Comment by interduo** [comment]
Jak już napisałem ten commit (https://github.com/BillTechPL/lms-billtech-plugin/commit/7f3bf857f067baf30a664d4af2cb394c75ebc45b) mam u siebie w systemie.

**Comment by MKaciuba** [comment]
Ok, zmyliło mnie, że podlinkowałeś https://github.com/BillTechPL/lms-billtech-plugin/blob/master/handlers/BillTechPaymentCashImportHandler.php#L13. W takim razie czy mógłbyś do tego maila dodać jeszcze wartość `var_dump($hookdata, true)` i podesłać do mnie?

**Comment by interduo** [comment]
Teraz w https://github.com/BillTechPL/lms-billtech-plugin/blob/master/handlers/BillTechPaymentCashImportHandler.php#L13 dodałem kod:

```
$msg=var_dump($hookdata, true);
mail('jkl@interduo.pl','BillTechPaymentCashImportHandler.php',$msg);
```

Dam Ci tego maila jutro dopiero po 11.

**Comment by interduo** [comment]
Dostałem pustego maila, czyli $hookdata puste

**Comment by interduo** [comment]
Zamiast var_dump zrobiłem print_r($hookdata) i odpaliłem testowo import

```
Array
(
    [cashimports] => Array
        (
            [0] => Array
                (
                    [id] => 98416
                    [date] => 1562709600
                    [value] => 1.00
                    [customer] => NIEPODAMBORODO
                    [description] => NIEPODAMBORODO
                    [customerid] => 635
                    [hash] => a5e2e1c5fa56caaf617a9d0140cae4c8
                    [closed] => 0
                    [sourceid] => 
                    [sourcefileid] => 2533
                    [idate] => 1562837893
                )

        )

)
```

**Comment by MKaciuba** [comment]
@interduo sprawdź https://github.com/BillTechPL/lms-billtech-plugin/commit/5bbc8d64e1e17f5556561ebbba09dd7954219108

**Comment by interduo** [comment]
Niestety to jeszcze nie to. 
Płatność nadal nie jest rozliczona.

**Comment by MKaciuba** [comment]
Czy wartość pola `description` wygląda tak:
`Opłata za saldo-20190522 ID: 681 re|f:20190522-331308 dotpay: 355898 M1|278-88906 (Wpłata BS)`? Separator to `|` czy `\|`?

**Comment by interduo** [comment]
Separator to znak `|`

**Comment by interduo** [comment]
Separator w polu description to pojedyńczy znak `|`.

**Comment by interduo** [comment]
```
Array
(
    [0] => Array
        (
            [id] => 98422
            [date] => 1562709600
            [value] => 126.00
            [customer] => RODOSRODO
            [description] => Opłata za saldo-20190709 ID: 361 re|f:20190709-338742 dotpay: 355898 M1|763-44428 (Wpłata BS)
            [customerid] => 361
            [hash] => dd346948825940f8ef3fdc03fd1cd109
            [closed] => 0
            [sourceid] => 
            [sourcefileid] => 2539
            [idate] => 1562844774
        )

)
```

**Comment by interduo** [comment]
https://github.com/BillTechPL/lms-billtech-plugin/blob/master/handlers/BillTechPaymentCashImportHandler.php#L18

to jest winne - prag_replace nie działa

**Comment by interduo** [comment]
```
# git diff
diff --git a/handlers/BillTechPaymentCashImportHandler.php b/handlers/BillTechPaymentCashImportHandler.php
index bc363c6..74110d6 100644
--- a/handlers/BillTechPaymentCashImportHandler.php
+++ b/handlers/BillTechPaymentCashImportHandler.php
@@ -15,7 +15,7 @@ class BillTechPaymentCashImportHandler
                        $description = $import['description'];
 
                        if (ConfigHelper::getConfig('billtech.cashimport_enabled', false) && $description) {
-                               preg_match('/ref:(\d{8}-\d{6})/', preg_replace('[,|]', '', $description), $matches);
+                               preg_match('/ref:(\d{8}-\d{6})/', preg_replace('/[|]/', '', $description), $matches);
                                if (isset($matches[1])) {
                                        $reference_number = $matches[1];
                                        $payment = $DB->GetRow("SELECT id, amount, closed, cashid FROM billtech_payments WHERE reference_number=? AND closed=0", array($reference_number));
```

**Comment by interduo** [comment]
Naprawiłem i działa. Jak wrzucisz do repo zamknij zgłoszenie.
