### ISSUE TITLE
Nie działa kasowanie tymczasowych wpłat BillTech Payments

### ISSUE THREAD

**Issue by interduo** [BillTechPL/lms-billtech-plugin#22]
Nie działa automatyczne kasowanie wpłat tymczasowych z komentarzem "BillTech Payments" z tabeli cash podczas czynności:
- importu wpłat za pomocą cashimport,
- przeminięcia ilości dni w zmiennej payment_expiration.

Te wpłaty na liście płatności są zaznaczone jako rozliczone (szare).

**Comment by interduo** [comment]
Ta płatność:

```
MariaDB [lmsdb]> SELECT * FROM billtech_payments WHERE id=4634;
+------+-----+------------+--------+-------+-----------------+------------------+------------+--------+--------+
| id   | ten | customerid | amount | title | document_number | reference_number | cdate      | closed | cashid |
+------+-----+------------+--------+-------+-----------------+------------------+------------+--------+--------+
| 4634 |     |       3528 |  58.00 |       | saldo-20190719  | 20190719-813207  | 1563560722 |      1 |   NULL |
+------+-----+------------+--------+-------+-----------------+------------------+------------+--------+--------+
1 row in set (0.00 sec)

```

W tym polu jest cashid = NULL i tutaj pewnie jest błąd.


Wpis który powinien zostać usunięty:
```
MariaDB [lmsdb]> SELECT * FROM cash WHERE id='413480';
+--------+------------+------+--------+-------+-------+------------+-------------------+-------+--------+----------+----------+
| id     | time       | type | userid | value | taxid | customerid | comment           | docid | itemid | importid | sourceid |
+--------+------------+------+--------+-------+-------+------------+-------------------+-------+--------+----------+----------+
| 413480 | 1563560722 |  100 |   NULL | 58.00 |  NULL |       3528 | BillTech Payments |  NULL |      0 |     NULL |     NULL |
+--------+------------+------+--------+-------+-------+------------+-------------------+-------+--------+----------+----------+
1 row in set (0.00 sec)
```

**Comment by interduo** [comment]
U @olimplan jest błąd:

```
PHP Fatal error:  Uncaught Error: Class 'BillTechPaymentCashImportHandler' not found in /var/www/lms.git/lib/LMSPluginManager/LMSPlugin.php:134
Stack trace:
#0 /var/www/lms.git/lib/LMSPluginManager/LMSPlugin.php(108): LMSPlugin->dispatcher('cashimport_afte...', Array)
#1 /var/www/lms.git/vendor/phine/observer/src/lib/Phine/Observer/Subject.php(177): LMSPlugin->receiveUpdate(Object(LMSPluginManager))
#2 /var/www/lms.git/lib/LMSPluginManager/LMSPluginManager.php(166): Phine\Observer\Subject->notifyObservers()
#3 /var/www/lms.git/lib/LMS.class.php(191): LMSPluginManager->executeHook('cashimport_afte...', Array)
#4 /var/www/lms.git/lib/LMSManagers/LMSCashManager.php(405): LMS->executeHook('cashimport_afte...', Array)
#5 /var/www/lms.git/lib/LMS.class.php(488): LMSCashManager->CashImportCommit()
#6 /var/www/lms.git/bin/lms-cashimport.php(170): LMS->CashImportCommit()
#7 {main}
  thrown in /var/www/lms.git/lib/LMSPluginManager/LMSPlugin.php on line 134
```

Ja u siebie nie widzę tego ale zapewne obu nas dotyczy.

**Comment by MKaciuba** [comment]
> PHP Fatal error:  Uncaught Error: Class 'BillTechPaymentCashImportHandler' not found in /var/www/lms.git/lib/LMSPluginManager/LMSPlugin.php:134
> Stack trace:
> #0 /var/www/lms.git/lib/LMSPluginManager/LMSPlugin.php(108): LMSPlugin->dispatcher('cashimport_afte...', Array)
> #1 /var/www/lms.git/vendor/phine/observer/src/lib/Phine/Observer/Subject.php(177): LMSPlugin->receiveUpdate(Object(LMSPluginManager))
> #2 /var/www/lms.git/lib/LMSPluginManager/LMSPluginManager.php(166): Phine\Observer\Subject->notifyObservers()
> #3 /var/www/lms.git/lib/LMS.class.php(191): LMSPluginManager->executeHook('cashimport_afte...', Array)
> #4 /var/www/lms.git/lib/LMSManagers/LMSCashManager.php(405): LMS->executeHook('cashimport_afte...', Array)
> #5 /var/www/lms.git/lib/LMS.class.php(488): LMSCashManager->CashImportCommit()
> #6 /var/www/lms.git/bin/lms-cashimport.php(170): LMS->CashImportCommit()
> #7 {main}
>   thrown in /var/www/lms.git/lib/LMSPluginManager/LMSPlugin.php on line 134

Coś tu chyba jest namieszane w instalacji wtyczki. Upewnijcie się, że wszystkie pliki są na miejscu.

**Comment by interduo** [comment]
U mnie się to nie pokazuje na instancji ale cashimport nie usuwa wpłat tymczasowych.

**Comment by interduo** [comment]
Czy dostarczone przeze mnie informacje są wystarczające do odwzorowania problemu u Ciebie na instancji testowej?

**Comment by MKaciuba** [comment]
To są dwa, nie powiązane problemy. Czy w tabelce `billtech_payments` jakikolwiek wiersz ma w kolumnie `cashid` inną wartość niż NULL?

**Comment by interduo** [comment]
Tylko jeden:
```
MariaDB [lmsdb]> SELECT * FROM billtech_payments WHERE cashid IS NOT NULL;
+------+-----+------------+--------+-------+-----------------+------------------+------------+--------+--------+
| id   | ten | customerid | amount | title | document_number | reference_number | cdate      | closed | cashid |
+------+-----+------------+--------+-------+-----------------+------------------+------------+--------+--------+
| 4640 |     |         51 |  30.00 |       | saldo-20190723  | 20190723-522265  | 1563861790 |      0 |  45932 |
+------+-----+------------+--------+-------+-----------------+------------------+------------+--------+--------+
```

**Comment by interduo** [comment]
To mimo wszystko cashid jest nieprawidłowe bo użytkownik po kliknięciu opłaty za FV może mieć kilka pozycji na niej.

**Comment by MKaciuba** [comment]
Spróbuj proszę przetestować rozliczanie tej konkretnej wpłaty. Np. ustawić cdate = 1561269790.

**Comment by interduo** [comment]
@MKaciuba czy u was na instancji testowej jest odwzorowywalny ten błąd?

**Comment by MKaciuba** [comment]
> @MKaciuba czy u was na instancji testowej jest odwzorowywalny ten błąd?

nie.

**Comment by interduo** [comment]
> Spróbuj proszę przetestować rozliczanie tej konkretnej wpłaty. Np. ustawić cdate = 1561269790.

Gdzie mam to cdate ustawić? I jaki test wykonać?

**Comment by interduo** [comment]
Mam plik importu z banku mogę wyłuskać tą pojedyńczą wpłatę i testować.

**Comment by MKaciuba** [comment]
`UPDATE billtech_payments SET cdate= 1561269790  WHERE id = 4640;`
Po chwili płatność powinna być rozliczona a wpis w cash powinien zniknąć.

**Comment by interduo** [comment]
```
MariaDB [lmsdb]> SELECT * FROM billtech_payments WHERE id = 4640;
+------+-----+------------+--------+-------+-----------------+------------------+------------+--------+--------+
| id   | ten | customerid | amount | title | document_number | reference_number | cdate      | closed | cashid |
+------+-----+------------+--------+-------+-----------------+------------------+------------+--------+--------+
| 4640 |     |         51 |  30.00 |       | saldo-20190723  | 20190723-522265  | 1561269790 |      1 |   NULL |
+------+-----+------------+--------+-------+-----------------+------------------+------------+--------+--------+
1 row in set (0.00 sec)
```

**Comment by interduo** [comment]
A wpis tymczasowy w tabeli cash o treści nadal jest.

**Comment by MKaciuba** [comment]
Ok, czy zniknął cash z id 45932?

**Comment by interduo** [comment]
> Ok, czy zniknął cash z id 45932?

Nie

**Comment by MKaciuba** [comment]
Ok czyli problem leży w `$LMS->DelBalance($payment['cashid']);`

**Comment by interduo** [comment]
Mi kasowanie z GUI LMS działa a widzę że korzysta z tej samej funkcji.

**Comment by MKaciuba** [comment]
Jeszcze jedno, żeby się upewnić. Wejdź proszę w zakładkę _Płatności BillTech_, znajdź tę płatność i oznacz ją najpierw jako nierozliczoną --> powinien powstać nowy wpis w cash. Zanotuj cashid z tabelki billtech_payments a następnie ustaw płatność jako rozliczoną. Czy wtedy wiersz z cash zniaka?

**Comment by interduo** [comment]
Na liście mam tą płatność jako szarą (mimo że wpis w tabeli cash jest).
Po kliknięciu przycisku dodaje się nowa, płatność nadal jest w tabelce jako rozliczona.
Każde kolejne kliknięcie przycisku dodaje nową płatność tymczasową.

**Comment by MKaciuba** [comment]
To, że zostaje szara jest normalne bo po prostu natychmiast zostaje ponownie rozliczona (nadal jest przeterminowana). Dziwne natomiast jest to, że wiersz cash nie znika. Czy możesz przetestować działanie `$LMS->DelBalance()` w izolacji? Np. wybrać wiersz z `cash`, który ma być usunięty np. 4634 i dodać w BillTechPaymentsUpdater na samym początku metody checkForUpdate taki kawałek kodu:
```
$LMS->DelBalance(4634);
```

**Comment by interduo** [comment]
Już pisałem - z historii operacji działa ponieważ kasujemy wpłaty tymczasowe z tego miejsca.

**Comment by interduo** [comment]
4634 to id płatności w tabeli billtech a nie płatności tymczasowej w tabeli cash. 

Ok zaraz spróbuję to potestować.

**Comment by interduo** [comment]
Dodanie tego kodu kasue wpis.

**Comment by interduo** [comment]
https://github.com/BillTechPL/lms-billtech-plugin/commit/5bbc8d64e1e17f5556561ebbba09dd7954219108

```
SHOW CREATE TABLE cashimport;
+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table      | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| cashimport | CREATE TABLE `cashimport` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `date` int(11) NOT NULL DEFAULT '0',
  `value` decimal(9,2) NOT NULL DEFAULT '0.00',
  `customer` text COLLATE utf8_polish_ci NOT NULL,
  **`description` text COLLATE utf8_polish_ci NOT NULL,**
  `customerid` int(11) NOT NULL DEFAULT '0',
  `hash` varchar(50) COLLATE utf8_polish_ci NOT NULL DEFAULT '',
  `closed` tinyint(1) NOT NULL DEFAULT '0',
  `sourceid` int(11) DEFAULT NULL,
  `sourcefileid` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `hash` (`hash`),
  KEY `customerid` (`customerid`),
  KEY `sourcefileid` (`sourcefileid`),
  KEY `sourceid` (`sourceid`)
) ENGINE=InnoDB AUTO_INCREMENT=99346 DEFAULT CHARSET=utf8 COLLATE=utf8_polish_ci |
+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

```

**Comment by interduo** [comment]
To nie to?

**Comment by MKaciuba** [comment]
Mógłbyś sprawdzić jaka jest wartość `$payment['cashid']` w https://github.com/BillTechPL/lms-billtech-plugin/blob/master/BillTechPaymentsUpdater.php#L75?

**Comment by interduo** [comment]
4640

**Comment by MKaciuba** [comment]
To nie jest `$payment['id']`?

**Comment by interduo** [comment]
To jest ID płatności z tabeli billtech_payments zamiast ID z tabeli cash.

**Comment by MKaciuba** [comment]
Czy na 100% wypisałeś `$payment['cashid']`?

**Comment by interduo** [comment]
![vim](https://user-images.githubusercontent.com/17087236/61888229-74273500-af03-11e9-8040-0f027251100a.png)

**Comment by MKaciuba** [comment]
Wypiszesz proszę `$payment['cashid']` zamiast `$payment['id']`?

**Comment by interduo** [comment]
Nie myślę już. To znak że już muszę kończyć pracę. Jutro to skończymy. Na tą chwilę robię cashimport = false.

**Comment by interduo** [comment]
46297

**Comment by interduo** [comment]
Nie działa odrozliczanie tylko w tym wpisie któremu zmieniłem cdate.
Odrozliczenie wpłaty powoduje dodanie wpisu billtech.
Rozliczenie wpłaty nie powoduje usunięcia tego wpisu.

**Comment by MKaciuba** [comment]
@interduo Mógłbyś zajrzeć jeszcze do logów czy nie ma tam jakichś błędów SQL? ew. zobacz czy https://github.com/BillTechPL/lms-billtech-plugin/commit/1848393515dd71e05baabef728c1847c883bcea2 coś zmienia.

**Comment by interduo** [comment]
@MKaciuba słabo. Bardzo.

W tabeli billtech_payments w kolumnie cashid pojawiają się nieprawidłowe ID.

Czy wiesz jaki jest tego skutek?
Podpowiedź: https://github.com/lmsgit/lms/blob/master/doc/lms.mysql#L1086-L1097

**Comment by MKaciuba** [comment]
@interduo potrzebuję trochę więcej informacji. Kiedy pojawiają się nieprawidłowe ID. Co dokładnie oznacza _nieprawidłowe_?

**Comment by interduo** [comment]
Już to rozkminiliśmy:

Problem leży tutaj:
https://github.com/lmsgit/lms/blob/master/lib/LMSDB_driver_mysqli.class.php#L354-L357
Brakuje tutaj w kodzie tej funkcji zmiennej table (MySQL tego nie obsługuje).

W związku z tym proponuję zastąpić tą funkcję bezpośrednim zapytaniem do bazy tam gdzie występuje ta funkcja.

**Comment by interduo** [comment]
Np. funkcja GetLastInsertID zwraca ostatnie id z tabeli logmessages zamiast id z tabeli cash.

**Comment by interduo** [comment]
W związku z czym GetLastID() w kodzie wtyczki zwracało nie to czego oczekujemy.
np w tabeli billtech_payments było np. 44601 co w tabeli cash było wpisem z 20XX roku.

Musimy teraz przez to wyciągnąć stare backupy i przywrócić brakujące wpisy z wielu tabel co zapewne będzie kosztować nas wiele pracy.

**Comment by interduo** [comment]
Na początek przed wywołaniem funkcji DelBalance proponuję warunek czy id jest wpłatą BillTechową czyli: wpis zawiera comment = "BillTech Payments" w tabeli cash.

**Comment by MKaciuba** [comment]
@interduo przetestujesz https://github.com/lmsgit/lms/commit/66b5be7d9a4061e4c09c5d5f8cfc733ca8a64696
+
https://github.com/BillTechPL/lms-billtech-plugin/commit/4d5a43dbccea203b970606e39884ef6d12cab16d

**Comment by interduo** [comment]
Dopisz proszę warunek, żeby kasował tylko wpłaty w których jest w cash.comment = 'BillTech Payments'.

**Comment by MKaciuba** [comment]
To trochę bez sensu. Jeśli id będą prawidłowe to ten warunek nie będzie miał znaczenia.

**Comment by interduo** [comment]
Lepiej dwa razy sprawdzić.

Z Twojego punktu widzenia to bez sensu. Z mojego nie - ponieważ nie wiesz ile zamieszania to spowodowało. Nie chcę przerabiać tego samego problemu z innego powodu.

**Comment by interduo** [comment]
Dasz radę dodać? Wykonam wtedy test ponownie.

**Comment by MKaciuba** [comment]
Jeśli chcesz, to dodaj sobie na czas testów taki warunek w swoim kodzie.

**Comment by interduo** [comment]
> A jeśli znów z jakiegoś powodu nie będą prawidłowe?

Oczekuję dodatkowego zabezpieczenia w kodzie, by taka sytuacja nie miała okazji się nawet powtórzyć przy tak newralgicznej czynności. Pal licho o powód bo piłeczkę można odbijać.

**Comment by interduo** [comment]
Dzięki. Zabieram się za testowanie.

**Comment by interduo** [comment]
Wrzuciłem commit LMSowy do nas.
Wrzuciłem do pluginu billtech 3 commity z tego zgłoszenia.
Poprawiłem cashid w tabeli billtech_payments.

Przycisk "Rozlicz" działa jak oczekujemy:
Usuwa wpłatę tymczasową, zaznacza płatność jako rozliczoną i robi cashid = NULL w tabeli billtechpayments.

Zobaczymy jeszcze jak jutrzejszy import.

**Comment by interduo** [comment]
Jest już lepiej - część wpłat się rozliczyła.

Nie rozliczyły się te:
```
MariaDB [lmsdb]> SELECT * FROM cash WHERE id = 413778;
+--------+------------+------+--------+-------+-------+------------+-------------------+-------+--------+----------+----------+
| id     | time       | type | userid | value | taxid | customerid | comment           | docid | itemid | importid | sourceid |
+--------+------------+------+--------+-------+-------+------------+-------------------+-------+--------+----------+----------+
| 413778 | 1564129966 |  100 |   NULL | 59.00 |  NULL |       2609 | BillTech Payments |  NULL |      0 |     NULL |     NULL |
+--------+------------+------+--------+-------+-------+------------+-------------------+-------+--------+----------+----------+
1 row in set (0.00 sec)

MariaDB [lmsdb]> SELECT * FROM cash WHERE id = 413785;
+--------+------------+------+--------+-------+-------+------------+-------------------+-------+--------+----------+----------+
| id     | time       | type | userid | value | taxid | customerid | comment           | docid | itemid | importid | sourceid |
+--------+------------+------+--------+-------+-------+------------+-------------------+-------+--------+----------+----------+
| 413785 | 1564380492 |  100 |     23 | 75.00 |  NULL |         32 | BillTech Payments |  NULL |      0 |     NULL |     NULL |
+--------+------------+------+--------+-------+-------+------------+-------------------+-------+--------+----------+----------+
1 row in set (0.00 sec)

MariaDB [lmsdb]> SELECT * FROM billtech_payments WHERE closed=0;
+------+-----+------------+--------+-------+-----------------+------------------+------------+--------+--------+
| id   | ten | customerid | amount | title | document_number | reference_number | cdate      | closed | cashid |
+------+-----+------------+--------+-------+-----------------+------------------+------------+--------+--------+
| 4645 |     |       2609 |  59.00 |       | saldo-20190726  | 20190726-674473  | 1564129966 |      0 | 413778 |
| 4647 |     |         32 |  75.00 |       | saldo-20190729  | 20190729-415563  | 1564380492 |      0 | 413785 |
+------+-----+------------+--------+-------+-----------------+------------------+------------+--------+--------+
2 rows in set (0.00 sec)

```

**Comment by MKaciuba** [comment]
@interduo były w cashimport?

**Comment by interduo** [comment]
Były. Po imporcie wpłaty wpadły w konto klienta. Płatność tymczasowa nie została usunięta.

**Comment by MKaciuba** [comment]
Czy była jakaś różnica pomiędzy wpłatami, które się rozliczyły, a wpłatami, które się nie rozliczyły?

**Comment by interduo** [comment]
```
grep 'DOTPAY' -a wyciag-2019-07-29.txt_imported | cut -f12 -d','
"Op�ata za saldo-20190726 dotpay: 35|5898 M2410-19413"
"Op�ata za saldo-20190726 ID: XXX re|f:20190726-817163 dotpay: 355898 M1|525-55342"
"Op�ata za saldo-20190728 ID: YYYY r|ef:20190728-847114 dotpay: 355898 M|1295-61850"
```
Brak ID w tytule przelewu.

**Comment by interduo** [comment]
Kasowanie wpłat tymczasowych po upływie określonego czasu w zmiennej działa.
Także temat zgłoszenia zamykam a to przenoszę do innego.

**Comment by interduo** [comment]
BTW wrzuć to do master'a
