### ISSUE TITLE
Brak ID/REF w tytule płatności BillTech

### ISSUE THREAD

**Issue by interduo** [BillTechPL/lms-billtech-plugin#23]
```
grep 'DOTPAY' -a wyciag-2019-07-29.txt_imported | cut -f12 -d','
"Op�ata za saldo-20190726 dotpay: 35|5898 M2410-19413"
"Op�ata za saldo-20190726 ID: XXX re|f:20190726-817163 dotpay: 355898 M1|525-55342"
"Op�ata za saldo-20190728 ID: YYYY r|ef:20190728-847114 dotpay: 355898 M|1295-61850"
```

_Originally posted by @interduo in https://github.com/BillTechPL/lms-billtech-plugin/issues/22#issuecomment-516386837_

**Comment by interduo** [comment]
Ok - mam kolejną bez ref:
`Opłata za saldo-20190730 dotpay: 35|5898 M1640-69190 (Wpłata BS)` to mamy w tytule płatności`

**Comment by interduo** [comment]
W tym przypadku cashid mamy nadany prawidłowo w tabeli billtech_payments.

**Comment by interduo** [comment]
@MKaciuba czy to znany wam problem? zaradzimy coś na to?

**Comment by MKaciuba** [comment]
@interduo zajmuję się tą sprawą. Dam znać jak uda mi się coś ustalić.

**Comment by interduo** [comment]
ok - thx

**Comment by MKaciuba** [comment]
@interduo były pewne problemy z dopasowaniem użytkownika LMS z użytkownikiem BillTech. Właśnie wdrażam zmiany w systemie BillTech, które powinny zapobiec tego typu sytuacji w przyszłości.
