### ISSUE TITLE
Kasowanie tymczasowych wpłat BillTech Payments - sprawdzanie salda

### ISSUE THREAD

**Issue by interduo** [BillTechPL/lms-billtech-plugin#26]
Doszło dzisiaj u nas do dziwnej sytuacji. Klient ma pobrane z karty pieniądze a my nie posiadamy przelewu na rachunku bankowym. Wpłata tymczasowa została usunięta. W związku z czym mamy sytuację kiedy klient myśli, że zapłacił sukcesywnie. Wpłata znajduje się w liście płatności "BillTech płatności".

Proponuję, żeby przed kasowaniem tymczasowej płatności sprawdzić czy jest już rozliczona lub nastąpiła jakakolwiek wpłata od ostatniego obciążenia.

W przypadku gdy jest przelew wykasuj płatność tymczasową, w przypadku kiedy nie ma przelewu - alertuj mailem.

**Comment by interduo** [comment]
@MKaciuba @bpetrynski minął miesiąc od zgłoszenia. Czy uda się wam wprowadzić poprawki do kodu?

**Comment by interduo** [comment]
Po rozmowie z @MKaciuba ustaliliśmy że najprostszą opcją jest przestawienie parametru wygaszania płatności tymczasowych na np. 10000 dni i raportowanie tych płatności ostatnych po przekroczeniu innego parametru np 8 dni. To uchroni przed tym oraz wszelkimi innymi możliwymi błędami (np zrypany numer referencyjny).

Zmianę w kodzie traktuję jako bugfixing/supportcase.

**Comment by interduo** [comment]
Płatności przeterminowane na liście "płatności billtech" mogłyby być prezentowane na czerwono i temat byłby z głowy - zaglądamy tam raz miesięcznie. Wtedy można by wyłapywać takie kwiatki.

**Comment by interduo** [comment]
Udałoby się wam zrobić prezentację wpłąt przeterminowanych na czerwono na liście wpłat?

**Comment by MKaciuba** [comment]
@interduo niezły pomysł. Możemy coś takiego zrobić.

**Comment by interduo** [comment]
Dzięki za ficzer.
