### ISSUE TITLE
PHP Warning przy wywołaniu BillTechPaymentsUpdater.php w lms-payments

### ISSUE THREAD

**Issue by olimplan** [BillTechPL/lms-billtech-plugin#27]
Codziennie z crona leci mi wywołanie lms-payments.php generujące faktury. Od czasu do czasu dostaję od crona maila z informacją:

PHP Warning:  Invalid argument supplied for foreach() in /var/www/lms.git/plugins/BillTech/BillTechPaymentsUpdater.php on line 136

**Comment by interduo** [comment]
Potwierdzam, że i u nas występuje czasami ten błąd ale akurat nie przy lms-payments.php tylko pojawia się w error_logu podczas normalnej pracy.

**Comment by MKaciuba** [comment]
@olimplan @interduo prośba o sprawdzenie czy problem występuje w najnowszej wersji.

**Comment by olimplan** [comment]
zaktualizowałem u siebie - teraz zostaje czekać, bo niestety ten błąd występował bardzo nieregularnie

**Comment by interduo** [comment]
@interduo my już nie notujemy problemów z tym. IMO można zamknąć.

**Comment by olimplan** [comment]
u nas też już nie zauważyłem w logach błędów - tak więc do zamknięcia :-)
