### ISSUE TITLE
Odznacz-rozlicz błąd

### ISSUE THREAD

**Issue by interduo** [BillTechPL/lms-billtech-plugin#28]
![odznacz-rozlicz](https://user-images.githubusercontent.com/17087236/77079221-f36bfa80-69f7-11ea-9594-7eaf160ec6c4.png)

Silnik: postgres

**Comment by MKaciuba** [comment]
@interduo problem został rozwiązany w https://github.com/BillTechPL/lms-billtech-plugin/commit/6195d72d7b7dfcead19ce04aa81d0f54744e024f. Prośba o aktualizację wtyczki.

**Comment by interduo** [comment]
Działa, dziękuję.
