### ISSUE TITLE
Brak automatycznego kasowania tymczasowych  niektórych wpłat

### ISSUE THREAD

**Issue by interduo** [BillTechPL/lms-billtech-plugin#29]
```
Oplata za saldo-20200316 ID: 4 ref:|20200316-654274 dotpay: 355898 M196|2-01340
Oplata za 02267/T/02/2020 ID: 4 ref|*20200312-450031 dotpay: 355898 M21|12-57902
```

@MKaciuba regexp przyjęty tutaj:
https://github.com/BillTechPL/lms-billtech-plugin/blob/01f36ab13b5a90d0a520dea397eb716f8fd931a1/handlers/BillTechPaymentCashImportHandler.php#L19

Nie bardzo gra. Prosimy o poprawki.

**Comment by MKaciuba** [comment]
@interduo oba wiersze nie zadziałały czy tylko drugi? Pytanie czemu w drugim wierszu znak ':' został zamieniony na '*'? Czy tak to wygląda po eksporcie z banku? Od nas to wychodzi jako:
`Opłata za 02267/T/02/2020 ID: 4 ref**:**20200312-450031 dotpay: 355898 M2112-57902`

**Comment by interduo** [comment]
1. Oba wiersze są problematyczne. 
2. To jest wkleiłem dostajemy z banku na importach.
