### ISSUE TITLE
Nie kasują się wpłaty tymczasowe billtech payments

### ISSUE THREAD

**Issue by interduo** [BillTechPL/lms-billtech-plugin#30]
Dla wpłat BillTech od 2020/05/13 nie kasują się wpłaty tymczasowe przy imporcie z banku.

**Comment by MKaciuba** [comment]
Czy w tytułach wpłat jest numer referencyjny? `ref: XXXXXXXX-XXXXXX`

**Comment by interduo** [comment]
Przypadek 1:
'Oplata za saldo-20200504 ID: 628 re|f:20200504-437046 dotpay: 355898 M1|694-79207' (przelew od DOTPAY)

Tutaj mamy ref z pionową kreską.

Przypadek 2:
'saldo-20200601|||RRN: E015300000998' (przelew od BILLTECH SPÓŁKA)

Ten drugi nie idzie.

**Comment by MKaciuba** [comment]
Rozumiem, dzięki. Naprawimy to asap.

**Comment by interduo** [comment]
Bardzo nieładnie prawda?:)

**Comment by MKaciuba** [comment]
Główny problem wynikał z tego, że po migracji na nową bramkę płatniczą, w tytułach przelewów brakowało numeru referencyjnego. Przez to wtyczka nie mogła powiązać przelewów z wpłatami tymczasowymi. Rozwiązaliśmy ten problem i od tej pory przelewy będą mieć prawidłowe tytuły. Dodatkowo, nowa bramka płatnicza nie przyjmuje w tytule przelewu znaku ":", dlatego zastąpiliśmy go spacją - wymagana jest aktualizacja wtyczki.
Co do wpłat tymczasowych utworzonych pomiędzy 2020/05/13, a naprawą, proponuję rozwiązanie w postaci ręcznego rozliczenia tych wpłat w zakładce _Płatności BillTech_. W imieniu swoim i całego zespołu BillTech najmocniej przepraszam za kłopot.

**Comment by interduo** [comment]
Teraz przyszedł przelew w którym nie ma ref:
ref null ID 4028 saldo-20200624|||RRN: E017600012895 (Wpłata BS) płatność nie została rozliczona automatycznie

**Comment by MKaciuba** [comment]
Ta płatność była wykonana 24 czerwca, czyli przed wprowadzeniem poprawki.

**Comment by interduo** [comment]
Nie ma nic o RRN tutaj:
https://github.com/BillTechPL/lms-billtech-plugin/blob/master/handlers/BillTechPaymentCashImportHandler.php#L19

**Comment by interduo** [comment]
np. wpłata z 20200708 jest "ref null"

**Comment by MKaciuba** [comment]
RRN to kod dodawany przez bramkę płatniczą imoje, można go zignorować. Sprawdzę o co chodzi z ref null.

**Comment by interduo** [comment]
Ok - wpłaty rozliczyłem sobie ręcznie ale kosztowało mnie to trochę czasu także dla mnie to niepilne już ale zapewne inni jeszcze o tym nie wiedzą ;-)
