### ISSUE TITLE
%billtech_btn - przycisk płaci saldo czy fakturę

### ISSUE THREAD

**Issue by interduo** [BillTechPL/lms-billtech-plugin#33]
Chciałem sobie w szablon wrzucić przycisk szybkiej zapłaty. Mam pytanko o akcję jaka się wydarzy po jego naciśnięciu:

a) płatności tylko wysyłanej przez lms-sendinvoices.php **faktury**,
b) płatność całego zaległego **salda** klienta,

Od razu zadam drugie pytanie jeśli wariant "a" - to czy możecie dokodować zmienną `%billtech_btn2`, która wyświetlałaby przycisk w szablonie wiadomości HTML ze spłatą całego zaległego salda?

**Comment by MKaciuba** [comment]
W nowej wtyczce klient będzie mógł opłacić saldo po przejściu na dowolną z płatności za pojedynczą fakturę.

**Comment by interduo** [comment]
Ok, a jeśli to będzie pierwsza płatność nowego klienta?

**Comment by MKaciuba** [comment]
Zakładaliśmy wcześniej, że skoro w BillTech będą wszystkie płatności danego klienta, to na tej podstawie można wywnioskować jego saldo. Wtedy klient po wejściu na dowolną płatność miałby możliwość przejścia na spłatę salda. 
![image](https://user-images.githubusercontent.com/9113506/90020607-5d8b8180-dcb0-11ea-873a-972562f89733.png)
Przewidzieliśmy też możliwość skierowania klienta od razu na spłatę salda, przez dodanie do dowolnego aktywnego linku do płatności parametru `type=balance`.
Faktycznie pojawia się problem, jeśli to jest pierwsza płatność tego klienta, bo wtedy w BT nie ma jeszcze jego wszystkich płatności. Musimy pomyśleć co z tym zrobić.

**Comment by MKaciuba** [comment]
Możemy zrobić w userpanelu tak, że po kliknięciu w dowolny przycisk, generowane są linki dla wszystkich nieopłaconych faktur danego klienta. W ten sposób będzie dostępna informacja o saldzie i wszystko będzie spójne. Myślimy jeszcze jak to zrobić, żeby link do salda mógłby być w mailu.

**Comment by interduo** [comment]
Ale kombinacje. Czy nie możecie po prostu zrobić %billtech_btn2 z inną wartością linku?

**Comment by MKaciuba** [comment]
Najprościej w tej sytuacji byłoby po prostu skierować klienta na ekran logowania do userpanelu i tam już będzie miał przycisk do spłaty salda.

**Comment by interduo** [comment]
Ja chcę by klient płacił jednym klikiem z maila. Bardzo dużo osób nie pamięta ID i hasła do eBok.

**Comment by MKaciuba** [comment]
> Ale kombinacje. Czy nie możecie po prostu zrobić %billtech_btn2 z inną wartością linku?
Niestety nie możemy. Spowodowałoby to niespójność w naszym systemie, który zakłada, że każda płatność jest za osobny dokument.

**Comment by interduo** [comment]
No to jak zrobić jedną płatność za np. 3 zaległe faktury?

**Comment by MKaciuba** [comment]
Na załączonym screenie jest zakładka "SPŁATA SALDA", która jest dostępna dla klienta po wejściu na płatność za dowolną z tych 3 faktur. Dodanie `type=balance` do któregokolwiek z tych linków spowoduje skierowanie klienta bezpośrednio na tę zakładkę. Tam może zrobić pojedynczą płatność za wszystkie 3 faktury.

>zakłada, że każda płatność jest za osobny dokument.

źle się wyraziłem. Chodzi o każdy link do płatności, ale można zrobić jedną płatność za kilka faktur, jeśli dla każdej istnieje aktywny link do płatności. https://docs.billtech.pl/pay/createLink#p%C5%82atno%C5%9B%C4%87-za-saldo

**Comment by interduo** [comment]
> Zakładaliśmy wcześniej, że skoro w BillTech będą wszystkie płatności danego klienta

To niestety błędne założenie - bo nie będą.

**Comment by MKaciuba** [comment]
Klient może wycofać zgodę a potem ją wznowić.

> W takiej sytuacji będzie po prostu traktowany jak nowy klient.

**Comment by interduo** [comment]
> W takiej sytuacji będzie po prostu traktowany jak nowy klient.

I nie będzie mógł zapłacić całego salda. Myślę, że nie warto robić regresu w stosunku do obecnej wtyczki.

**Comment by MKaciuba** [comment]
Myślimy nad tym jak to zrobić, żeby była taka możliwość.

**Comment by pablos-billtech** [comment]
We obecnej wersji wtyczki jest rozróżnienie pomiędzy przycisk opłaty za fakturę (%billtech_btn) i przycisk opłaty za saldo (%billtech_balance_btn).
