### ISSUE TITLE
Problem z wykonaniem płatności

### ISSUE THREAD

**Issue by interduo** [BillTechPL/lms-billtech-plugin#4]
po kliknięciu w "OPŁAĆ TERAZ" wyskakuje błąd:\
![billtech_blad](https://user-images.githubusercontent.com/17087236/32542686-aad95b22-c473-11e7-9301-86a12f48a4b3.png)

**Comment by MKaciuba** [comment]
Czy numer konta na pewno jest ustawiony i jest prawidłowym numerem IBAN?

**Comment by interduo** [comment]
Ok zapomniałem uzupełnić to na instancji testowej. Już to robię.
