### ISSUE TITLE
Nie rozliczające się wpłaty przy imporcie

### ISSUE THREAD

**Issue by interduo** [BillTechPL/lms-billtech-plugin#40]
Mam garść wpłat, które mimo ostatniej poprawki na długość ref'a nie rozliczyły się. Potrzebuję uruchomić dokładnie to co LMS robi po imporcie w pluginie.

Np. testowa wpłata
`
112,20200807,12900,10500028,19300018,"72105010251000009032170186","06870700068981000500004418","BILLTECH GROUP SP£<9c>KA Z OGRANICZON<8f>","Interduo",0,87070006,"ref 20200806-214517 ID 4418 saldo-2|0200806||RRN: E021900006320","","","51","","07-08-2020/97208540442","0002020080700200008"`

```
lmsdb=# SELECT * FROM billtech_payments WHERE reference_number = '20200806-214517';
 ten | customerid | amount | title | document_number | reference_number |   cdate    | closed | cashid |  id  
-----+------------+--------+-------+-----------------+------------------+------------+--------+--------+------
     |       4418 | 129.00 |       | saldo-20200806  | 20200806-214517  | 1596707260 |      0 | 483585 | 1828
(1 wiersz)
```

Widnieje nadal u nas jako nierozliczona.

Znalazłem kod:
https://github.com/BillTechPL/lms-billtech-plugin/blob/master/handlers/BillTechPaymentCashImportHandler.php

Niestety nie widzę opcji w obecnym stanie by go uruchomić ręcznie i zrobić jakiś dokładniejszy debug. 

Czy dopiszecie do skryptu np argument np. --try-last-import, który powodowałby, że billtech próbowałby rozliczać wpłaty z ostatniego importu?

**Comment by MKaciuba** [comment]
Rozumiem, że zrobienie importu drugi raz wygeneruje duplikaty w cash?

**Comment by interduo** [comment]
ZTCP jest na to zabezpieczenie w postaci sum kontrolnych.
Więc nie wleci to w import to raczej - co sprawi, że dane do hooka nie będą pełne.

Z mojej strony przejrzałem logi postgresa i apache ... tam jest czysto.

**Comment by MKaciuba** [comment]
Ok, rozumiem, jak wycina przed hookiem to faktycznie ten sposób nie zadziała. Czy dane z importu, w szczególności tytuł przelewu są gdzieś odpisywane?

**Comment by interduo** [comment]
Nie rozumiem co znaczy "odpisywane".

**Comment by MKaciuba** [comment]
Czy zapisuje się gdzieś w bazie danych?

**Comment by interduo** [comment]
U nas wygląda to tak:
1. Nasz skrypt importuje z banku plik txt.
2. Uruchamiamy lms-cashimport.php
3. BillTech uruchamia się po imporcie wpłat.

Zobacz tabelę cash oraz cashimport.

Tak btw dlaczego nie wydzieliliście kodu billtechowego do synchronizacji i dopasowywania wpłat w oddzielnym skrypt np. BillTechSynchronize-Crontab.php tylko pod hooki?

**Comment by MKaciuba** [comment]
> Tak btw dlaczego nie wydzieliliście kodu billtechowego do synchronizacji i dopasowywania wpłat w oddzielnym skrypt np. BillTechSynchronize-Crontab.php tylko pod hooki?

Żeby ułatwić instalację wtyczki.

**Comment by interduo** [comment]
I, żeby utrudnić debugowanie i korzystanie z LMSa później. ;-)
Proponuję zmianę koncepcji bo czasami jest tak, że BillTechUpdater wprowadza lagi w korzystaniu z UI.

Administratorzy radzą sobie z wrzucaniem rzeczy do Crontaba - mają już ich w LMS co najmniej kilka.

**Comment by MKaciuba** [comment]
Dzięki! Weźmiemy to pod uwagę.

**Comment by pablos-billtech** [comment]
Z tego co widzę przeoczyliśmy znak $ w ostatnim PR. Ten dolar oznaczałby, że ref jest na końcu description. Wprowadzamy poprawkę i prośba o rozliczenie przeszłych wpłat ręcznie.

**Comment by interduo** [comment]
O dzięki za poprawkę, zobaczymy jutro czy to jest jedyny powód.
Właśnie dlatego tą metodę przydałoby się móc wywołać ręcznie, żeby nie robić ręcznego rozliczania.

**Comment by interduo** [comment]
Kilka wpłat się dzisiaj rozliczyło. Mam jeszcze pytanie co do opóźnień bo zauważyłem że np. dzisiaj wpłata z 10.08 się rozliczyła a mam w kolejce nierozliczoną wpłatę z 08.08. Od czego zależy kiedy dojdzie do nas przelew od was? 
Jakie powinno być maksymalne opóźnienie?

**Comment by MKaciuba** [comment]
Zazwyczaj jest to do dwóch dni roboczych. Zależy od tego kiedy płatność jest zrealizowana. My zlecamy wypłatę natychmiast, natomiast bramka imoje przeważnie realizuje przelew wychodzący o godzinie 12 kolejnego dnia roboczego. Dalej to już kwestia sesji elixir.

**Comment by MKaciuba** [comment]
> Kilka wpłat się dzisiaj rozliczyło ale dopiero kiedy rozładuje mi się wszystko z oczekujących wpłat to zamknę to zgłoszenie.

Te kilka, które już były w cashimport, chyba będzie trzeba ręcznie przepchnąć.

**Comment by interduo** [comment]
Na tą chwilę nie ma co rozliczać bo przelewy nie przyszły jeszcze

**Comment by interduo** [comment]
Jest git obecnie.

**Comment by awbnet** [comment]
Wiedziałem, żeby poczekać przed uruchomieniem 😛
