### ISSUE TITLE
Przeniesienie synchronizacji do odrębnego pliku

### ISSUE THREAD

**Issue by interduo** [BillTechPL/lms-billtech-plugin#44]
Celem usunięcia okazjonalnych lagów w GUI.

**Comment by interduo** [comment]
@MKaciuba @bpetrynski czy to zostanie zrobione?

**Comment by MKaciuba** [comment]
@interduo właśnie pojawiła się nowa wersja wtyczki, w której ten problem jest rozwiązany. Przepisaliśmy prawie całą wtyczkę od nowa, zmieniliśmy sposób generowania linków oraz m.in. przenieśliśmy mechanizm synchronizacji informacji o wykonanych płatnościach do crona.
