### ISSUE TITLE
Nieprawidłowe lokalizacje przycisków OPŁAĆ TERAZ

### ISSUE THREAD

**Issue by interduo** [BillTechPL/lms-billtech-plugin#5]
![billtech-zakladkatwojekonto](https://user-images.githubusercontent.com/17087236/32547553-1595e43a-c483-11e7-90d4-94d9405978cd.png)

W tym wariancie klient ma nierozliczoną ostatnią fakturę. Przyciski opłać teraz wyświetlają się przy starszych pozycjach.

**Comment by MKaciuba** [comment]
Czy faktury są oznaczone jako rozliczone na liście faktur w panelu admina?

**Comment by interduo** [comment]
Napisałem pod zdjęciem, że tak :)

**Comment by MKaciuba** [comment]
Mógłbyś zajrzeć do bazy i sprawdzić jaka jest wartość kolumny 'closed' dla tych faktur? Przycisk powinien wyświetlać tylko dla dokumentów z type = 0 i closed = 0

**Comment by interduo** [comment]
OK - wiem o co chodzi, to są zobowiązania niewynikające z faktur.

**Comment by MKaciuba** [comment]
Czyli działa?

**Comment by interduo** [comment]
Nie - nie działa. Po prostu klient ma saldo ujemne z powodu ręcznie dodanych zobowiązań nie wynikających z faktur.

Saldo ma różne od sumy wystawionych faktur.
Stąd ta problematyczna sytuacja.

**Comment by MKaciuba** [comment]
Jeśli zobowiązania nie zostaną oznaczone jako rozliczone (parametr closed == 1) nie ma możliwości schowania przycisków. Możliwość opłacenia salda jest w zakładce Finanse/Saldo i tam przycisk pojawia się jeśli saldo jest ujemne.

**Comment by interduo** [comment]
![klient_test](https://user-images.githubusercontent.com/17087236/32554590-9900a51e-c49a-11e7-8365-2d3c5ad2518f.png)

**Comment by interduo** [comment]
![bilans_klienta](https://user-images.githubusercontent.com/17087236/32554665-da81a4ac-c49a-11e7-9a78-cf2a0ef62418.png)

**Comment by MKaciuba** [comment]
W jaki sposób dodawane są zobowiązania niebędące fakturami?

**Comment by interduo** [comment]
![dodawanie](https://user-images.githubusercontent.com/17087236/32557336-25bf2b7c-c4a2-11e7-8070-389ad19fa5d3.png)

np. tak - tabelka customerbalancebox tam masz puste pole do wpisania i wybór zobowiązanie po kliknięciu zapisz transakcja ląduje u klienta.

**Comment by MKaciuba** [comment]
Już wiem o co chodzi. Niedługo będzie poprawka.

**Comment by interduo** [comment]
Najs :)

**Comment by MKaciuba** [comment]
Wyłączamy przycisk "Opłać teraz" dla zobowiązań niebędących fakturami.
