### ISSUE TITLE
Niedziałający opłać teraz z zakładki FINANSE

### ISSUE THREAD

**Issue by interduo** [BillTechPL/lms-billtech-plugin#6]
![oplacteraz_z_finanse](https://user-images.githubusercontent.com/17087236/32547914-381a9e6e-c484-11e7-9132-c539b767bfd3.png)

**Comment by MKaciuba** [comment]
Podeślij proszę na maila wygenerowany link.

**Comment by MKaciuba** [comment]
Kwota wyliczała się dla zobowiązań niebędących fakturami. Dla tych zobowiązań całkowicie wyłączyliśmy przycisk płatności więc ten problem nie wystąpi.
