### ISSUE TITLE
Konstrukcja pluginu

### ISSUE THREAD

**Issue by interduo** [BillTechPL/lms-billtech-plugin#7]
https://github.com/BillTechPL/lms-billtech-plugin/blob/master/install.sh#L3-L5

To jest napisane w inny sposób niż konstrukcja pluginu przewiduje zerknijcie do:
lms/plugins/PluginExample

Skutek taki, że po instalacji pluginu git mnie informuje o zmianach.

**Comment by MKaciuba** [comment]
Racja to mogłoby być zrobione lepiej. Niestety nie mam dostępu do LMS plus i przykładowych pluginów, żeby zobaczyć jak to powinno być zrobione. Wiem, że można w pluginie dodać ścieżkę z szablonami ale te szablony mają identyfikatory z prefixem "module:" i są ładowane przy pomocy customowego resource resolvera. Ten resource resolver ma wpisaną na sztywno ścieżkę do szablonów danego modułu i nie znalazłem sposobu na "wstrzyknięcie" szablony przez wtyczkę. Może masz jakiś pomysł?

**Comment by interduo** [comment]
@MKaciuba masz dostęp do LMS gdzie jest przykładowy plugin https://github.com/lmsgit/lms/tree/master/plugins/PluginExample zerknij jak to jest tam zrobione.

**Comment by MKaciuba** [comment]
Tak, widziałem to ale tutaj podmieniony jest szablon z core'a LMSa a nie z userpanelu. 
`$SMARTY->display('welcome/welcome.html')`.
W userpanelu szablony są używane tak:
`$SMARTY->display('module:finances.html');`
W resource resolverze dla prefixu "module:" (Smarty_Resource_Userpanel_Module.php) jest zawsze brana ścieżka danego modułu więc mechanizm wstrzyknięcia szablonu nie działa.

**Comment by interduo** [comment]
Dopytaj @chilek jak to sensownie zrobić. Wg mnie to co teraz zrobiliście będzie problematyczne w utrzymaniu, przy każdym update LMS może się sypać (jeśli update będzie odnosił się do tych linii),

Głośno myślę: lepiej zamiast podmiany całego pliku z szablonem dorzucić zmiany za pomocą:
git chery-pick hashidcommita (?)

**Comment by interduo** [comment]
To już naprawione.
