### ISSUE TITLE
Nadpisywanie się klucza

### ISSUE THREAD

**Issue by interduo** [BillTechPL/lms-billtech-plugin#8]
Proszę o dodanie sprawdzania w skrypcie install.sh sprawdzania czy klucz istnieje przed wygenerowaniem go.

Jeśli istnieje klucz i wybierzemy install.sh nadpisuje się klucz który wam wysłaliśmy. :)

**Comment by MKaciuba** [comment]
Jeśli klucz istnieje to nie ma potrzeby uruchamiania tego skryptu. Jedyne co robi to generuje parę kluczy i przeładowuje autoloadera.

**Comment by interduo** [comment]
Co w momencie kiedy instalujesz plugin od nowa i wygrywasz tam klucze? Po powrocie z gór wytestuje go ponownie.

Co do tego zgłoszenia wystarczy jeden mały warunek i sprawa będzie rozwiązana.
