### ISSUE TITLE
Komentarz transakcji tymczasowej

### ISSUE THREAD

**Issue by interduo** [BillTechPL/lms-billtech-plugin#87]
Obecnie jest tak:
Transakcja tymczasowa ma komentarz zawsze domyślnie "BillTech Payments" lub coś ze zmiennej.

Pożądany efekt:
Oprócz samego komentarza przydałoby się dorzucić refid lub inny jej identyfikator.

Czasami zdarza się, że do cash wlatuje kilka transakcji tymczasowych a przelew przychodzi jeden.

**Comment by smiecielica** [comment]
W aktualnej wersji wpłąty tymczasowe są zatytułowane jako "Wpłata online za: {numer_faktury}" - [Zrzut ekranu z panelu LMS](https://user-images.githubusercontent.com/91327379/162974669-4b7fa781-a16e-4476-a984-29a25be71364.png).

W ostatnim zamkniętym [PRze](https://github.com/BillTechPL/lms-billtech-plugin/pull/89) poprawiliśmy znikające numery faktur w przypadku rozliczenia wpłaty tymczasowej, a następnie ponownie jej dodania.

**Comment by interduo** [comment]
@smiecielica niestety nie mam możliwości zaktualizowania wtyczki ze względu na to, że wprowadziliście regres jeśli chodzi o udostępnianie danych naszych transakcji.

Czy w obecnej wersji jest możliwość działania wtyczki jak dawniej?
(zatrzymaliśmy się na:
commit 995506272f9a6116aec4105914149a362bbe9a9a
Author: MKaciuba <MKaciuba@users.noreply.github.com>
Date:   Tue Aug 25 18:37:20 2020 +0200)
