### ISSUE TITLE
Warning: openssl_sign(): supplied key param cannot be coerced into a private key

### ISSUE THREAD

**Issue by interduo** [BillTechPL/lms-billtech-plugin#9]
![blad](https://user-images.githubusercontent.com/17087236/35483564-f3b51a24-0443-11e8-8e2a-5c1c403f6932.png)

**Comment by MKaciuba** [comment]
Co jest wpisane w konfiguracji pod kluczem billtech.private_key?

**Comment by interduo** [comment]
install.sh uzupełniło mi zmienną billtech.private_key jako "plugins/BillTech/lms.pem".
Plik tam istnieje i ma uprawnienia +r

**Comment by MKaciuba** [comment]
Spróbowałbym zdebugować czy zawartość klucza jest prawidłowo ładowana z pliku. Czy directories.sys_dir wskazuje na /var/www/html/lmpt? Ścieżka do klucza powstaje poprzez sklejenie: 
directories.sys_dir + / + illtech.private_key.

**Comment by interduo** [comment]
```
$ grep sys_dir /etc/lms/lms.ini
sys_dir = /var/www/html/lmpt/
```

Próbowałem z / i bez.

**Comment by MKaciuba** [comment]
Czy klucz prywatny znajduje się w katalogu /var/www/html/lmpt/plugins/BillTech?

**Comment by interduo** [comment]
root@lmpt:/var/www/html/lmpt/plugins/BillTech# ls -la lms.pub
-rw-r--r-- 1 root root 451 sty 23 15:09 lms.pub

**Comment by MKaciuba** [comment]
a lms.pem?

**Comment by interduo** [comment]
`chmod +r lms.pem`

Pomogło.
